# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate Contagion Index (C++ implementation)
NULL

contagion_cpp <- function(x) {
    .Call(`_mucha_contagion_cpp`, x)
}

